import type { Metadata } from "next";
import "../globals.css";
import {
  geistMono,
  geistSans,
  IRANYekanFont,
} from "@/modules/Theme/helpers/font";
import ThemeLayout from "@/modules/Theme/widgets/ThemeLayout";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  // Ensure that the incoming `locale` is valid
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html lang={locale} dir="rtl">
      <body className={`${IRANYekanFont.className} antialiased`}>
        <NextIntlClientProvider messages={messages}>
          <ThemeLayout>{children}</ThemeLayout>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
